"""Initial migration

Revision ID: 1add96b25861
Revises: 
Create Date: 2025-07-07 15:35:33.263686

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1add96b25861'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('depenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('libelle', sa.String(length=100), nullable=False),
    sa.Column('montant', sa.Float(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('matieres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('nom')
    )
    op.create_table('utilisateurs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('mot_de_passe', sa.String(length=200), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('prenom', sa.String(length=100), nullable=False),
    sa.Column('telephone', sa.String(length=20), nullable=True),
    sa.Column('role', sa.Enum('ADMIN', 'ENSEIGNANT', 'ELEVE', 'PARENT', 'COMPTABLE', name='roleutilisateur'), nullable=False),
    sa.Column('date_creation', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('date_mise_a_jour', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('enseignants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('prenom', sa.String(length=100), nullable=False),
    sa.Column('telephone', sa.String(length=20), nullable=True),
    sa.Column('matricule', sa.String(length=50), nullable=False),
    sa.Column('utilisateur_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateurs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('matricule')
    )
    op.create_table('classes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('salle', sa.String(length=50), nullable=False),
    sa.Column('niveau', sa.String(length=50), nullable=False),
    sa.Column('annee_scolaire', sa.String(length=20), nullable=False),
    sa.Column('enseignant_principal_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['enseignant_principal_id'], ['enseignants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('enseignant_matiere',
    sa.Column('enseignant_id', sa.Integer(), nullable=True),
    sa.Column('matiere_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['enseignant_id'], ['enseignants.id'], ),
    sa.ForeignKeyConstraint(['matiere_id'], ['matieres.id'], )
    )
    op.create_table('eleves',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('prenom', sa.String(length=100), nullable=False),
    sa.Column('matricule', sa.String(length=50), nullable=False),
    sa.Column('sexe', sa.String(length=1), nullable=False),
    sa.Column('date_naissance', sa.Date(), nullable=True),
    sa.Column('adresse', sa.String(length=255), nullable=True),
    sa.Column('utilisateur_id', sa.Integer(), nullable=False),
    sa.Column('classe_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['classe_id'], ['classes.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['utilisateurs.id'], ),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateurs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('matricule')
    )
    op.create_table('emplois_du_temps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jour', sa.String(length=20), nullable=False),
    sa.Column('heure_debut', sa.Time(), nullable=False),
    sa.Column('heure_fin', sa.Time(), nullable=False),
    sa.Column('classe_id', sa.Integer(), nullable=False),
    sa.Column('enseignant_id', sa.Integer(), nullable=False),
    sa.Column('matiere_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['classe_id'], ['classes.id'], ),
    sa.ForeignKeyConstraint(['enseignant_id'], ['enseignants.id'], ),
    sa.ForeignKeyConstraint(['matiere_id'], ['matieres.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('valeur', sa.Float(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('periode', sa.String(length=50), nullable=False),
    sa.Column('eleve_id', sa.Integer(), nullable=False),
    sa.Column('matiere_id', sa.Integer(), nullable=False),
    sa.Column('enseignant_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['eleve_id'], ['eleves.id'], ),
    sa.ForeignKeyConstraint(['enseignant_id'], ['enseignants.id'], ),
    sa.ForeignKeyConstraint(['matiere_id'], ['matieres.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('paiements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('eleve_id', sa.Integer(), nullable=False),
    sa.Column('montant', sa.Float(), nullable=False),
    sa.Column('date_paiement', sa.Date(), nullable=False),
    sa.Column('periode', sa.String(length=50), nullable=False),
    sa.Column('methode', sa.String(length=50), nullable=True),
    sa.Column('statut', sa.String(length=20), nullable=True),
    sa.Column('recu', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['eleve_id'], ['eleves.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('recu')
    )
    op.create_table('presences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('eleve_id', sa.Integer(), nullable=False),
    sa.Column('classe_id', sa.Integer(), nullable=False),
    sa.Column('professeur_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('statut', sa.String(length=10), nullable=False),
    sa.Column('justifiee', sa.Boolean(), nullable=True),
    sa.Column('motif', sa.String(length=255), nullable=True),
    sa.Column('commentaire', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['classe_id'], ['classes.id'], ),
    sa.ForeignKeyConstraint(['eleve_id'], ['eleves.id'], ),
    sa.ForeignKeyConstraint(['professeur_id'], ['enseignants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('presences')
    op.drop_table('paiements')
    op.drop_table('notes')
    op.drop_table('emplois_du_temps')
    op.drop_table('eleves')
    op.drop_table('enseignant_matiere')
    op.drop_table('classes')
    op.drop_table('enseignants')
    op.drop_table('utilisateurs')
    op.drop_table('matieres')
    op.drop_table('depenses')
    # ### end Alembic commands ###
